env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=BezierKit/BezierKit.xcodeproj
    - IOS_SCHEME=BezierKit_iOS
    - IOS_SDK=iphonesimulator13.2
    - OSX_SCHEME=BezierKit_Mac
    - OSX_SDK=macosx10.15
jobs:
  include:
  - name: Linux SPM
    os: linux
    dist: bionic
    env: SWIFT_VERSION=swift-5.3-RELEASE
  - name: iOS Min System
    os: osx
    osx_image: xcode11.2
    env: DESTINATION="OS=10.3.1,name=iPhone 5" SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
  - name: iOS
    os: osx
    osx_image: xcode11.2
    env: DESTINATION="OS=13.2.2,name=iPad Pro (12.9-inch) (3rd generation)" SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
  - name: MacOS
    os: osx
    osx_image: xcode11.2
    env: DESTINATION="arch=x86_64"SCHEME="$OSX_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES" POD_LINT="NO"
  - name: WebAssembly
    os: osx
    osx_image: xcode13.2
before_install:
  - ./travis/before_install.sh
script:
  - ./travis/script.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 5
